config/routes.rb
Rails.application.routes.draw do
  root "flights#index"

  resources :flights do
	collection do
		post :lookup
	end
  end

  resources :bookings

end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :departures, class_name: 'Flight', foreign_key: 'origin_id'
	has_many :arrivals, class_name: 'Flight', foreign_key: 'destination_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	has_many :passengers
	has_many :flights
	accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
	#associations
	belongs_to :origin, class_name: 'Airport'
	belongs_to :destination, class_name: 'Airport'
	has_many :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
	belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

    def index
	@bookings = Booking.all

    end

    def new
        #Logic for chosen flight info display
        @booking_flight = nil
        @booking_flight_date = nil
        @booking_flight_origin = nil
        @booking_flight_arrival = nil
        @booking_flight_id = nil
        @booking_passenger_count = nil
        @flight_id = nil
        @search = params['passenger_count']
        if @search.present?
            #Converts model query results into arrays to be accessed for display in views
            @flight_id = params['flight_id']
            @booking_flight = Flight.where(id: @flight_id)
            @booking_flight_name = @booking_flight.map{ |f| f.name }
            @booking_flight_date = @booking_flight.map{ |f| f.departure_date }
            @booking_flight_origin = @booking_flight.map{ |f| f.origin.airport_code }
            @booking_flight_destination = @booking_flight.map{ |f| f.destination.airport_code }
            @booking_flight_id = @booking_flight.map{ |f| f.id }
            @booking_passenger_count = params['passenger_count']
        end
        #Logic for creating booking/passenger
        @booking = Booking.new
        @booking_passenger_count.to_i.times { @booking.passengers.build }
    end

    def show
        @booking = Booking.find(params[:id])
    end

    def create
        @booking_new = Booking.new(booking_params)
        if @booking_new.save!
            redirect_to root_path
        else
            render :new
        end
    end

    private

    def booking_params
        params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
    def index
        #Logic for search form that creates arrays for simple_form collections
        @flights = Flight.all
        @flights_origins = Flight.all.map{ |f| [f.origin.airport_code, f.origin.id] }
        @flights_destinations = Flight.all.map{ |f| [f.destination.airport_code, f.destination.id] }
        @flights_dates = Flight.all.map{ |f| [f.departure_date, f.departure_date] }
        #Logic for populating post-search menu
        @flight_search_results = nil
        @flight_search_results_names = nil
        #Logic for search results lookup that parses nested URL key-value pairs for query purposes
        @search = params[:origin_id]
        if @search.present?
            @origin = params['origin_id']
            @destination = params['destination_id']
            @departure_date = params['departure_date']
            @flight_search_results = Flight.where(origin_id: @origin, destination_id: @destination, departure_date: @departure_date)
            @flight_search_results_names = @flight_search_results.map{ |f| [f.name, f.id] }
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_booking_flight_info.html.erb
<h1 class='is-size-4'>Name of flight: <%= @booking_flight_name[0] %></h1>
<h1 class='is-size-4'>Date of flight: <%= @booking_flight_date[0] %></h1>
<h1 class='is-size-4'>Flight origin airport: <%= @booking_flight_origin[0] %></h1>
<h1 class='is-size-4'>Flight destination airport: <%= @booking_flight_destination[0] %></h1>

app/views/bookings/_new_booking_form.html.erb
<%= form_with url:'/bookings', model: @booking, local:true do |form| %>
    <%= form.hidden_field :flight_id, value: @flight_id %>
    <h1 class="is-size-4">Fill out passenger info:</h1>
    <ul>
        <%= form.fields_for :passengers do |passengers_form| %>
            <%= passengers_form.hidden_field :id, value:nil %>
            <li>
                <%= passengers_form.label :name %>
                <%= passengers_form.text_field :name %>
                <%= passengers_form.label :email %>
                <%= passengers_form.text_field :email %>
            </li>
        <% end %>
    </ul>
    <button type="submit" class="button is-outlined" style="margin-top:10px">Confirm your booking</button>
<% end %>

app/views/bookings/index.html.erb
<% @bookings.each do |booking| %>
<div class='columns'>
<div class='column is-half'>
<article class="message">
  <div class="message-header">
    <p>Booking for <%= booking.passengers[0].name %></p>
  </div>
  <div class="message-body">
    Passenger list:
    <% booking.passengers.each do |passenger| %>
	<ol>
	<%= passenger.name %>
	</ol>
	<% end %>
	<%= Flight.find_by(id: booking.flight_id).name %>
    Departure date:
    <%= Flight.find_by(id: booking.flight_id).departure_date %>
  </div>
</article>
</div>
</div>
<% end %>

app/views/bookings/new.html.erb
<div class='columns'>
<div class='column is-half' style='margin-left:450px'>
<h2 class='is-size-2'>Create your booking</h2>
<div class='box'>
	<%= render 'booking_flight_info' %>
	<%= render 'new_booking_form' %>
</div>
</div>

app/views/bookings/show.html.erb
<%= @bookings.flights.do %>
    <p><%= flight.origin %>
<% end %> 

app/views/flights/_search_form.html.erb
<div class="columns">
<div class="column is-one-quarter">
<div class="box">
<!-- Form Name -->

<%= simple_form_for :search, url: "/flights", method: :get do |f| %>

<legend>Search for a flight:</legend>

<!-- Select Basic -->
<div class="field">
  <label class="label" for="selectbasic-0">Departure flight</label>
  <div class="control">
  	<div class="select">
	    <select id="selectbasic-0" name="origin_id" class="">
            <%= @flights_origins.each do |origin| %>
	            <option value= <%= origin[1] %> ><%= origin[0] %></option>
            <% end %>
	    </select>
	</div>
  </div>
</div>

<!-- Select Basic -->
<div class="field">
  <label class="label" for="selectbasic-2">Arrival flight</label>
  <div class="control">
  	<div class="select">
	    <select id="selectbasic-2" name="destination_id" class="">
        <%= @flights_destinations.each do |destination| %>
            <option value= <%= destination[1] %> ><%= destination[0] %></option>
        <% end %>
	    </select>
	</div>
  </div>
</div>

<!-- Select Basic -->
<div class="field">
  <label class="label" for="selectbasic-2">Select date of flight</label>
  <div class="control">
  	<div class="select">
	    <select id="selectbasic-2" name="departure_date" class="">
        <%= @flights_dates.each do |date| %>
            <option value= <%= date[0] %> ><%= date[0] %></option>
        <% end %>
	    </select>
	</div>
  </div>
</div>

<!-- Button -->
<div class="field">
  <div class="control">
  <%= f.button :submit, 'Search', class: "button is-success is-outlined" %>
  </div>
</div>

<% end %>
</div>
</div>
</div>

app/views/flights/_search_results.html.erb
<div class='columns'>
<div class='column is-one-quarter'>
<div class='box'>
<%= simple_form_for :flight_select, url: new_booking_path, method: :get do |f| %>

<!-- Select Basic -->
<div class="field">
  <label class="label" for="selectbasic-0">Matching flights:</label>
  <div class="control">
	<% unless @flight_search_results.empty? %>
  	<div class="select">
	    <select id="selectbasic-0" name="flight_id" class="">
            <%= @flight_search_results_names.each do |name| %>
	            <option value= <%= name[1] %> ><%= name[0] %></option>
            <% end %>
	    </select>
	<% else %>
	No matching flights, please make another choice
	<% end %>
	</div>
  </div>
</div>

<!-- Select Basic -->
<div class="field">
  <label class="label" for="selectbasic-0">Number of passengers:</label>
  <div class="control">
	<% unless @flight_search_results.empty? %>
  	<div class="select">
	    <select id="selectbasic-0" name="passenger_count" class="">
            <%= @flight_search_results_names.each do |name| %>
	            <option value= <%= 1 %> ><%= 1 %></option>
		    <option value= <%= 2 %> ><%= 2 %></option>
		    <option value= <%= 3 %> ><%= 3 %></option>
		    <option value= <%= 4 %> ><%= 4 %></option>
            <% end %>
	    </select>
	<% else %>
	No matching flights, please make another choice
	<% end %>
	</div>
  </div>
</div>

<!-- Button -->
<div class="field">
  <div class="control">
  <%= f.button :submit, 'Book', class: "button is-success is-outlined" %>
  </div>
</div>

<% end %>
</div>
</div>
</div>

app/views/flights/index.html.erb
<%= render 'search_form' %>

<% unless @flight_search_results.nil? %>
    <%= render 'search_results' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightProjectTop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <nav class="navbar has-background-primary" role="navigation" aria-label="main navigation">
  <div class="navbar-brand has-text-link-white">
    <a class="navbar-item" href="#">
      <nav class="breadcrumb" aria-label="breadcrumbs">
  	<ul>
    		<li><a href="/bookings"><h1 class="is-size-4 has-text-white">Bookings</h1></a></li>
    		<li><a href="/"><h1 class="is-size-4 has-text-white">Search flights</h1></a></li>
  	</ul>
      </nav>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
</nav>

  <body>
    <%= yield %>
  </body>
</html>